# QUERY FIELD
INIT_QUERY_MASTER = '''SELECT count(*) FROM sqlite_master WHERE type= "table" AND name = "METADATA";'''
QUERY_METADATA = '''SELECT * FROM METADATA;'''
QUERY_MUSIC = '''SELECT * FROM MUSIC;'''
QUERY_AKA = '''SELECT * FROM AKA;'''
QUERY_MEME = '''SELECT * FROM MEME;'''

# DROP THEM ALL!
DROP_METADATA = '''DROP TABLE IF EXISTS METADATA;'''
DROP_MUSIC = '''DROP TABLE IF EXISTS MUSIC;'''
DROP_AKA = '''DROP TABLE IF EXISTS AKA;'''
DROP_MEME = '''DROP TABLE IF EXISTS MEME;'''

# SET TABLES
SET_METADATA = '''
    CREATE TABLE METADATA(
    METADATA_VER INT PRIMARY KEY NOT NULL ,
    SDVX_VER INT NOT NULL ,
    FIX_VER INT NOT NULL ,

    MAP_SIZE INT NOT NULL);'''
SET_MUSIC = '''
    CREATE TABLE MUSIC(

    MID INT PRIMARY KEY NOT NULL ,
    NAME VARCHAR NOT NULL ,
    NAME_YO VARCHAR NOT NULL ,
    ARTIST VARCHAR NOT NULL ,
    ARTIST_YO VARCHAR NOT NULL ,
    MUSIC_ASCII VARCHAR NOT NULL ,
    BPM_MAX INT NOT NULL ,
    BPM_MIN INT NOT NULL ,
    DATE INT NOT NULL ,
    VERSION INT NOT NULL ,
    INF_VER INT ,

    NOV_LV INT ,
    NOV_ILL VARCHAR ,
    NOV_EFF VARCHAR ,
    NOV_NTS INT ,
    NOV_PEK INT ,
    NOV_TMM INT ,
    NOV_TRK INT ,
    NOV_HDT INT ,
    NOV_OHD INT ,
    
    ADV_LV INT ,
    ADV_ILL VARCHAR ,
    ADV_EFF VARCHAR ,
    ADV_NTS INT ,
    ADV_PEK INT ,
    ADV_TMM INT ,
    ADV_TRK INT ,
    ADV_HDT INT ,
    ADV_OHD INT ,
    
    EXH_LV INT ,
    EXH_ILL VARCHAR ,
    EXH_EFF VARCHAR ,
    EXH_NTS INT ,
    EXH_PEK INT ,
    EXH_TMM INT ,
    EXH_TRK INT ,
    EXH_HDT INT ,
    EXH_OHD INT ,
    
    INF_LV INT ,
    INF_ILL VARCHAR ,
    INF_EFF VARCHAR ,
    INF_NTS INT ,
    INF_PEK INT ,
    INF_TMM INT ,
    INF_TRK INT ,
    INF_HDT INT ,
    INF_OHD INT ,
    
    MXM_LV INT ,
    MXM_ILL VARCHAR ,
    MXM_EFF VARCHAR ,
    MXM_NTS INT ,
    MXM_PEK INT ,
    MXM_TMM INT ,
    MXM_TRK INT ,
    MXM_HDT INT ,
    MXM_OHD INT ,);'''
SET_AKA = '''CREATE TABLE AKA (AID INT PRIMARY KEY NOT NULL, NAME VARCHAR);'''
SET_MEME = '''CREATE TABLE SEARCH (MID INT PRIMARY KEY NOT NULL, MEME_STR VARCHAR);'''
